/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: CreadorDeMu (https://sketchfab.com/creadordemu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mirage-2000-5-pikachu-pilot-a361c655f09d43b9bbf2820151198012
Title: Mirage 2000-5 - Pikachu Pilot
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const { scene } = useGLTF('/models/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  return (
    <group {...props} dispose={null}>
      <group position={[0.165, 0.171, 2.829]} scale={0.025}>
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh geometry={nodes.Object_77.geometry} material={materials.Material_160} skeleton={nodes.Object_77.skeleton} />
        <skinnedMesh geometry={nodes.Object_78.geometry} material={materials.Material_161} skeleton={nodes.Object_78.skeleton} />
        <skinnedMesh geometry={nodes.Object_79.geometry} material={materials.Material_162} skeleton={nodes.Object_79.skeleton} />
        <skinnedMesh geometry={nodes.Object_80.geometry} material={materials.Material_163} skeleton={nodes.Object_80.skeleton} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials['R-77']} />
      <mesh geometry={nodes.Object_6.geometry} material={materials['R-77']} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['R-27_2']} position={[0.057, -0.123, 0]} rotation={[0, 0.017, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['R-27_2']} />
      <mesh geometry={nodes.Object_12.geometry} material={materials['AGM-65_Maverick']} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Hellfire} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Hellfire} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.color_ffffff} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.color_676767} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.material} />
      <mesh geometry={nodes.Object_22.geometry} material={materials.color_6a202a} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.color_707070} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.color_7d7d7d} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.color_751e10} />
      <mesh geometry={nodes.Object_26.geometry} material={materials['0136_Charcoal']} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.color_818380} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.color_a9aba6} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.color_000000} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.color_dcce6e} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.color_b8b8b8} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.color_7a7a7a} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.color_d8d8d8} />
      <mesh geometry={nodes.Object_34.geometry} material={materials.color_6b6b6b} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_36.geometry} material={materials.color_a39894} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Material_39} position={[0, 1.559, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_40.geometry} material={materials.Material_39} position={[-0.203, -0.286, 3.186]} rotation={[-0.017, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.Material_39} position={[0, 1.227, 2.269]} scale={0.003} />
      <mesh geometry={nodes.Object_44.geometry} material={materials['03_-_Default']} position={[0, 0, -3.395]} scale={0.003} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Material_39} position={[0, 1.559, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Material_39} position={[2.287, 0.017, -4.151]} scale={0.003} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Material_39} position={[-2.287, 0.017, -4.151]} scale={0.003} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Material_39} position={[0, 0, -3.395]} scale={0.003} />
      <mesh geometry={nodes.Object_54.geometry} material={materials['03_-_Default']} position={[0, 1.227, 2.269]} scale={0.003} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.Material_39} position={[-0.203, -0.302, 2.325]} rotation={[-0.026, 0, Math.PI / 2]} scale={0.003} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.Material_39} position={[0.203, -0.286, 3.186]} rotation={[-0.017, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.Material_39} position={[0, -0.499, -1.592]} scale={0.003} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Material_39} position={[0, 1.401, -5.743]} rotation={[-Math.PI / 9, 0, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.Material_25} position={[0, 0, -2.533]} rotation={[0, -Math.PI / 2, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.Material_25} position={[0, 0, -2.533]} rotation={[0, -Math.PI / 2, 0]} scale={0.003} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.Material_39} position={[0.223, -0.333, -1.067]} scale={0.003} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.Material_39} position={[-0.223, -0.333, -1.067]} scale={0.003} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.Material_39} position={[0, 0, -3.395]} scale={0.003} />
    </group>
  )
}

useGLTF.preload('/models/scene.gltf')
